<a href="https://colab.research.google.com/github/ashwinijadamali/Phyton-using-DA-and-ML/blob/master/Day3_session_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Write a Pandas program to create and display a one-dimensional array using series  containing  event numbers upto 10000
#tip : use List Comprehension
#ds = pd.Series([0,2, 4, 6, 8..... 10000]) 


In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


.Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
tip : use List Comprehension ds = pd.Series([0,2, 4, 6, 8..... 10000])

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)

0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

In [ ]:
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]

In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]


In [ ]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


.Write a Pandas program to convert a NumPy array to a Pandas series.

In [ ]:

import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


Write a Pandas program to convert a given Series to an array.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


Write a Pandas program to sort a given Series.
Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]

In [ ]:
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


Write a Pandas program to create a subsets of a given series based on value and condition.
Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5


In [ ]:
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000

In [ ]:
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


Write a Pandas program to get the elements of an array values into column-wise.
Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}

In [ ]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


Write a Pandas program to display the first 10 rows of the DataFrame for any particular three fields

In [ ]:
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])


!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials


auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

downloaded = drive.CreateFile({'id':'1hzxXR0uL-JosrCjV6JNn4g9FRMttT5rP'}) # replace the id with id of file you want to access
downloaded.GetContentFile('movies_metadata.csv') 

import pandas as pd
xyz = pd.read_csv('movies_metadata.csv') 
print(xyz.head(1))



Write a Pandas program to get the details of the seventh movie of the DataFrame for any particular three fields #(movie_metadata.csv file).

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
seventh_movie = df.iloc[3]
print("Details of the seventh movie:")
print(seventh_movie)

Write a Pandas program to sort the Data/

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
result = df[['title', 'genres']]
print("Details of title and genres:")
print(result)


Write a Pandas program to sort the DataFrame based on country and language from dataset of movie_metadata.csv

In [ ]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
# Create a smaller dataframe
small_df = df[['title', 'release_date', 'budget', 'revenue', 'runtime']]
result = small_df.sort_values('release_date')
print("DataFrame based on country and language.")
print(result)

Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable

In [ ]:
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 

Original Array:
[[0.56206638 0.57190439 0.20954965 0.61994187]
 [0.74174585 0.49834623 0.21793546 0.10974077]
 [0.64748156 0.53645858 0.64396015 0.21035339]
 [0.13480599 0.79231369 0.14858711 0.22538877]]


Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values

In [ ]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.48209312 0.15036801 0.92523716 0.81727583 0.41329414 0.44373426
  0.44102071 0.10402858 0.67901335 0.31013163]
 [0.31195459 0.64325659 0.49803735 0.85216344 0.24598117 0.16906368
  0.90232272 0.77366406 0.54609254 0.24104174]
 [0.9014605  0.43809587 0.42845553 0.31224396 0.93969182 0.44861168
  0.39105862 0.73826442 0.5778371  0.47910575]
 [0.99235434 0.3875056  0.34650732 0.23059465 0.87408955 0.61090184
  0.3480456  0.91590453 0.03357921 0.8810734 ]
 [0.24254901 0.14422348 0.61233141 0.27580966 0.53190993 0.57856939
  0.43799681 0.36649495 0.70473155 0.7323678 ]
 [0.65601802 0.2707955  0.32682423 0.70841785 0.12330383 0.57745323
  0.03817738 0.8360653  0.22261405 0.83524435]
 [0.96267371 0.49444934 0.27212805 0.58517664 0.15274601 0.11277638
  0.98233166 0.66405674 0.24744647 0.88359961]
 [0.86023503 0.73772242 0.15623139 0.59616463 0.76553555 0.90582003
  0.50285741 0.93973087 0.20396483 0.71583538]
 [0.7271602  0.04112282 0.15399971 0.4445712  0.18704775 0.97462


17.Write a NumPy program to generate 8 random integers between 100 and 300

In [ ]:
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)

[154 261 258 275 171 111 249 183]


Write a NumPy program to create a random integer nos of size 20 and sort it

In [ ]:
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.55212421 0.84847069 0.33877173 0.99814882 0.50413045 0.59336156
 0.46236984 0.23087448 0.65776799 0.19105968 0.06551682 0.04361158
 0.89596255 0.50828778 0.57899814 0.15992478 0.54206828 0.02859337
 0.24074083 0.21884406]
Sorted array:
[0.02859337 0.04361158 0.06551682 0.15992478 0.19105968 0.21884406
 0.23087448 0.24074083 0.33877173 0.46236984 0.50413045 0.50828778
 0.54206828 0.55212421 0.57899814 0.59336156 0.65776799 0.84847069
 0.89596255 0.99814882]
